# Generated by Django 4.0.5 on 2022-06-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('order', models.PositiveIntegerField(verbose_name='заказ №')),
                ('sum_dol', models.PositiveIntegerField(verbose_name='стоимость,$')),
                ('sum_rub', models.PositiveIntegerField(verbose_name='стоимость,руб.')),
                ('delivery_time', models.DateField(verbose_name='сроки поставки')),
            ],
        ),
    ]
