# Generated by Django 4.0.5 on 2022-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.CharField(max_length=10, verbose_name='сроки поставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sum_dol',
            field=models.CharField(max_length=10, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sum_rub',
            field=models.CharField(max_length=10, verbose_name='стоимость,руб.'),
        ),
    ]
